---
- name: Issue Let's Encrypt certificate for {{ item.domain }}
  ansible.builtin.command:
    cmd: >
      certbot certonly
      --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
      --dns-cloudflare-propagation-seconds 60
      --non-interactive
      --agree-tos
      --email {{ item.email }}
      -d {{ item.domain }}
      -d www.{{ item.domain }}
    creates: "/etc/letsencrypt/live/{{ item.domain }}/fullchain.pem"
  loop: "{{ letsencrypt_domains }}"
  notify: Reload nginx
  tags: certbot_issue
