---
- name: Ensure /etc/letsencrypt directory exists
  ansible.builtin.file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: certbot_credentials

- name: Deploy Cloudflare credentials file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/certbot/cloudflare.ini.j2"
    dest: /etc/letsencrypt/cloudflare.ini
    owner: root
    group: root
    mode: "0600"
  tags: certbot_credentials
