auth,authpriv.*                  /var/log/auth.log
kern.*                           /var/log/kern.log
cron.*                           /var/log/cron.log
if $programname == 'sudo' then   /var/log/sudo.log
& stop
*.emerg                          :omusrmsg:*
